# Generated by Django 4.2.6 on 2023-10-10 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
